### ISSUE TITLE
Toggle playlist doesnt work like before.

### ISSUE THREAD

**Issue by jkwnki** [gthreepw00d/mpv-iptv#4] opened 2020-12-28 21:41 UTC
Toggle playlist with \ or right click only works when playlist is displayed for the first time.
After selecting a channel, bringing up the playlist again isn't possible anymore.

Please fix.

Thank you in advance.

**Comment by gthreepw00d** [comment] 2020-12-29 13:16
Broken after update to mpv 0.33?
Then it looks like #3. 
Also there is temporary workaround in comments there.

**Comment by gthreepw00d** [comment] 2020-12-30 09:19
Duplicate of #3

**Closed as completed** 2020-12-30 09:18 UTC
